<template>
    <!-- Formulários -->
    <b-card no-body class="mt-4">
        <b-tabs card>
            <b-tab title="Dados Pessoais" active>
                <b-card-text>
                    <dados-pessoais-atualizar
                    :post="post"
                    :inserirEstagiario="inserirEstagiario"
                    :validaNome="validaNome"
                    :nomeValido="nomeValido"
                    :validaCodEstudante="validaCodEstudante"
                    :codValido="codValido"
                    :validaContratante="validaContratante"
                    :contratanteValido="contratanteValido"
                    :validaEndereco="validaEndereco"
                    :enderecoValido="enderecoValido"
                    :validaCep="validaCep"
                    :cepValido="cepValido"
                    :validaBairro="validaBairro"
                    :bairroValido="bairroValido"
                    :validaComplemento="validaComplemento"
                    :complementoValido="complementoValido"
                    :validaEstado="validaEstado"
                    :estadoValido="estadoValido"
                    :validaCelular="validaCelular"
                    :celularValido="celularValido"
                    :validaNaturalidade="validaNaturalidade"
                    :naturalidadeValida="naturalidadeValida"
                    :validaNacionalidade="validaNacionalidade"
                    :nacionalidadeValida="nacionalidadeValida"
                    :validaRaca="validaRaca"
                    :racaValida="racaValida"
                    :validaCpf="validaCpf"
                    :cpfValido="cpfValido"
                    :validaRg="validaRg"
                    :rgValido="rgValido"
                    :validaEmail="validaEmail"
                    :emailValido="emailValido"
                    :validaInstituicao="validaInstituicao"
                    :instituicaoValida="instituicaoValida"
                    :validaCurso="validaCurso"
                    :cursoValido="cursoValido"
                    :cartoes="cartoes"
                    :estados="estados"
                    :instituicoes="instituicoes"
                    :cursos="cursos"
                    :departamentos="departamentos"
                    :supervisores="supervisores"
                    :vagas="vagas"
                    />
                </b-card-text>
            </b-tab>
            <b-tab title="Informações Contratuais">
                <b-card-text>
                    <informacoes-contratuais-atualizar
                    :post="post"
                    :departamentos="departamentos"
                    :supervisores="supervisores"
                    :inserirEstagiario="inserirEstagiario"
                    :vagas="vagas"
                    :statusVaga="statusVaga"
                    :selectVaga="selectVaga"
                    :validaVaga="validaVaga"
                    :vagaValida="vagaValida"
                    :validaDepartamento="validaDepartamento"
                    :departamentoValido="departamentoValido"
                    :validaSetor="validaSetor"
                    :setorValido="setorValido"
                    :validaSupervisor="validaSupervisor"
                    :supervisorValido="supervisorValido"
                    :validaHorarioEntrada="validaHorarioEntrada"
                    :horarioEntradaValido="horarioEntradaValido"
                    :validaHorarioSaida="validaHorarioSaida"
                    :horarioSaidaValido="horarioSaidaValido"
                    :validaSituacao="validaSituacao"
                    :situacaoValida="situacaoValida"
                    />
                </b-card-text>
            </b-tab>
            <b-tab title="Recesso">
                <b-card-text>
                    <recesso-atualizar
                    :post="post"/>
                </b-card-text>
            </b-tab>
            <b-tab title="Dados Bancários">
                <b-card-text>
                    <dados-bancarios 
                    :post="post"
                    :inserirEstagiario="inserirEstagiario"
                    />
                </b-card-text>
            </b-tab>
        </b-tabs>
    </b-card>
    <!-- /Formulários -->
</template>

<script>
export default {
    props: [
        "post",
        "inserirEstagiario",
        "validaNome",
        "nomeValido",
        "validaCodEstudante",
        "codValido",
        "validaContratante",
        "contratanteValido",
        "validaEndereco",
        "enderecoValido",
        "validaCep",
        "cepValido",
        "validaBairro",
        "bairroValido",
        "validaComplemento",
        "complementoValido",
        "validaEstado",
        "estadoValido",
        "validaCelular",
        "celularValido",
        "validaNaturalidade",
        "naturalidadeValida",
        "validaNacionalidade",
        "nacionalidadeValida",
        "validaRaca",
        "racaValida",
        "validaCpf",
        "cpfValido",
        "validaRg",
        "rgValido",
        "validaEmail",
        "emailValido",
        "validaInstituicao",
        "instituicaoValida",
        "validaCurso",
        "cursoValido",
        "cartoes",
        "estados",
        "instituicoes",
        "cursos",
        "departamentos",
        "supervisores",
        "vagas",
        "departamentos",
        "supervisores",
        "vagas",
        "statusVaga",
        "selectVaga",
        "validaVaga",
        "vagaValida",
        "validaDepartamento",
        "departamentoValido",
        "validaSetor",
        "setorValido",
        "validaSupervisor",
        "supervisorValido",
        "validaHorarioEntrada",
        "horarioEntradaValido",
        "validaHorarioSaida",
        "horarioSaidaValido",
        "validaSituacao",
        "situacaoValida"
    ]}
</script>

<style>
.card-body {
    height: auto;
}
</style>
